<div class="modal-body text-center" id="printThis">
                    <div class="position-absolute" id="box-qrcode">
                        <div class="d-flex align-items-end" >
                            <p class="text-light text-center px-5 font-weight-bold">Acesse www.e-cardapio.com.br/web/<?= $cardapio['slug'] ?> e crie o seu agora mesmo, ou escaneie o código QR ao lado</p>
                            <canvas id="qr"></canvas>
                        </div>
                    </div>
                    <img src="<?= PATH ?>assets/admin/images/banner-qr.jpg" class="d-block w-100">
                </div>