<div class="text-center" id="printThis">
    <div class="position-absolute" id="box-qrcode">
        <div class="d-flex align-items-end" >
            <p class="text-light text-center px-5 font-weight-bold">Acesse www.e-cardapio.com.br/web/<?= $cardapio['slug'] ?> e crie o seu agora mesmo, ou escaneie o código QR ao lado</p>
            <canvas id="qr"></canvas>
        </div>
    </div>
    <img src="<?= PATH ?>assets/admin/images/banner-qr.jpg" class="d-block w-100">
</div>

<script src="<?= PATH ?>assets/admin/plugins/qrious/qrious.min.js"></script>
<script>
      (function() {
        var qr = new QRious({
		  size: 180,
          value: '<?= PATH.'web/'.$cardapio['slug'] ?>'
		});
		$('#qr').attr('src', qr.toDataURL());
      })();
</script>