<footer class="footer bg-primary py-3 pl-3">
	<span class="text-right">
		<a target="_blank" class="text-light" href="<?= PATH ?>">eCardapio</a>
	</span>
</footer>

</div>
<!-- END main -->


<script src="<?= PATH ?>assets/admin/js/jquery.min.js"></script>

<script src="<?= PATH ?>assets/admin/plugins/dom-to-image/dom-to-image.js"></script>
<!-- sweet alert-->
<script src="<?= PATH ?>assets/admin/plugins/sweet-alert/sweetalert2@9.js"></script>

<script src="<?= PATH ?>assets/admin/js/popper.min.js"></script>
<script src="<?= PATH ?>assets/admin/js/bootstrap.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/fontselect/jquery.fontselect.min.js"></script>

<script src="<?= PATH ?>assets/admin/plugins/qrious/qrious.min.js"></script>
<script>
      (function() {
        var qr = new QRious({
		  size: 180,
          value: '<?= PATH.'web/'.$cardapio['slug'].'?t='.base64_encode($cardapio['slug'].$cardapio['id_cardapio']) ?>'
		});
		console.log('<?= base64_encode($cardapio['slug'].$cardapio['id_cardapio']) ?>');
		$('#qr').attr('src', qr.toDataURL());
      })();
</script>
<!-- mask -->
<script src="<?= PATH ?>assets/admin/plugins/mask/src/jquery.mask.js"></script>

<!--js do cardapio -->
<script src="<?= PATH ?>assets/admin/js/categoria.js"></script>
<script src="<?= PATH ?>assets/admin/js/cardapio.js"></script>

<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/parsley.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/pt-br.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/jQuery.filer/jquery.filer.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/jQuery.filer/custom.js"></script>

</body>

</html>