
	<footer class="footer">
		<span class="text-right">
		<a target="_blank" href="<?= PATH ?>">eCardapio</a>
		</span>
		<span class="float-right">
		Powered by <a target="_blank" href="https://www.pikephp.com/free-bootstrap4-admin-template"><b>Pike Admin</b></a>
		</span>
	</footer>

</div>
<!-- END main -->

<script src="<?= PATH ?>assets/admin/js/modernizr.min.js"></script>
<script src="<?= PATH ?>assets/admin/js/jquery.min.js"></script>
<script src="<?= PATH ?>assets/admin/js/moment.min.js"></script>
		
<script src="<?= PATH ?>assets/admin/js/popper.min.js"></script>
<script src="<?= PATH ?>assets/admin/js/bootstrap.min.js"></script>

<script src="<?= PATH ?>assets/admin/js/detect.js"></script>
<script src="<?= PATH ?>assets/admin/js/fastclick.js"></script>
<script src="<?= PATH ?>assets/admin/js/jquery.blockUI.js"></script>
<script src="<?= PATH ?>assets/admin/js/jquery.nicescroll.js"></script>
<script src="<?= PATH ?>assets/admin/js/jquery.scrollTo.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/parsley.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/pt-br.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/jQuery.filer/jquery.filer.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/jQuery.filer/custom.js"></script>
<!-- App js -->
<script src="<?= PATH ?>assets/admin/js/pikeadmin.js"></script>

<!-- BEGIN Java Script for this page -->
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

	<script>
		$(document).ready(function() {			
			'use-strict';	
			$('[data-toggle="tooltip"]').tooltip()
			// data-tables
			$('#datatable').DataTable({
				"language":{
					"sEmptyTable": "Nenhum registro encontrado",
					"sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
					"sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
					"sInfoFiltered": "(Filtrados de _MAX_ registros)",
					"sInfoPostFix": "",
					"sInfoThousands": ".",
					"sLengthMenu": "_MENU_ resultados por página",
					"sLoadingRecords": "Carregando...",
					"sProcessing": "Processando...",
					"sZeroRecords": "Nenhum registro encontrado",
					"sSearch": "Pesquisar",
					"oPaginate": {
						"sNext": "Próximo",
						"sPrevious": "Anterior",
						"sFirst": "Primeiro",
						"sLast": "Último"
					},
					"oAria": {
						"sSortAscending": ": Ordenar colunas de forma ascendente",
						"sSortDescending": ": Ordenar colunas de forma descendente"
					}
				}
			});	
		} );		
	</script>
<!-- END Java Script for this page -->

</body>
</html>