<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>eCardapio - Painel Administrativo</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= PATH ?>assets/admin/images/favicon.png" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link href="<?= PATH ?>assets/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?= PATH ?>assets/admin/css/switch.css" rel="stylesheet" type="text/css" />

    <!-- Font Awesome CSS -->
    <link href="<?= PATH ?>assets/admin/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Colorpicker CSS -->
    <link href="<?= PATH ?>assets/admin/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">

    <!-- Fontpicker CSS -->
    <link href="<?= PATH ?>assets/admin/plugins/fontselect/fontselect-alternate.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?= PATH ?>assets/admin/css/style.css" rel="stylesheet" type="text/css" />

    <!-- JQuery.filer -->
    <link href="<?= PATH ?>assets/admin/plugins/jQuery.filer/jquery.filer.css" rel="stylesheet" type="text/css" />
    <link href="<?= PATH ?>assets/admin/plugins/jQuery.filer/themes/jquery.filer-dragdropbox-theme.css" rel="stylesheet" type="text/css" />

    <style>
        .parsley-error {
            border-color: #ff5d48 !important;
        }

        .parsley-errors-list.filled {
            display: block;
        }

        .parsley-errors-list {
            display: none;
            margin: 0;
            padding: 0;
        }

        .parsley-errors-list>li {
            font-size: 12px;
            list-style: none;
            color: #ff5d48;
            margin-top: 5px;
        }

        ::-webkit-scrollbar {
            width: 10px;
            height: 10px;
        }

        /* aqui é para personalizar o fundo da barra, neste caso estou colocando um fundo cinza escuro*/
        ::-webkit-scrollbar-track {
            background: #333;
        }

        /* aqui é a alça da barra, que demonstra a altura que você está na página
        estou colocando uma cor azul clara nela*/
        ::-webkit-scrollbar-thumb {
            background: #F55e61;
        }

        #box-qrcode {
            right: 2rem;
            bottom: 1.5rem;
        }

        @media screen {
            #printSection {
                display: none;
            }
        }

        @media print {
            body * {
                visibility: hidden;
            }

            #printSection,
            #printSection * {
                visibility: visible;
            }

            #printSection {
                position: absolute;
                left: 0;
                top: 0;
            }
        }
    </style>
    <!-- END CSS for this page -->

</head>

<body>

    <nav class="navbar bg-primary fixed-top py-1" style="box-shadow: 0px -6px 13px 5px #000000b0;">
        <a href="<?= PATH ?>admin"><img alt="Logo" src="<?= PATH ?>assets/site/img/icon-ecardapio-white.png" width="80px" /></a>

        <?= message('message') ?>

        <div class="btn-group my-2 my-sm-0 ml-xl-auto mr-xl-3">
            <a <?=($flag_produtos == 0)?"style='pointer-events:none;'":""?> href="<?= PATH . 'web/' . slugify($usuario['estabelecimento']) ?>" class="btn btn-outline-light px-lg-4" target="_blank" rel="noopener noreferrer"><i class="fa fa-eye pr-xl-2" aria-hidden="true"></i><span class="d-none d-sm-inline-block">Visualizar</span></a>
            <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modalQR"><i class="fa fa-qrcode pr-2" aria-hidden="true"></i>Gerar QRCode</a>
            </div>
        </div>
        <form action="<?= PATH ?>admin/produtos/busca" method="GET" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-2 w-auto" name="produto" type="text" placeholder="Buscar produto">
            <button class="btn btn-transparent text-dark my-2 my-sm-0 btn-search" type="submit"><i class="fa fa-search pr-2" aria-hidden="true"></i></button>
        </form>
        <div class="btn-group">
            <button type="button" class="btn btn-transparent dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="<?= PATH ?>assets/admin/images/avatars/avatar7.png" width="40px" alt="Profile image" class="bg-light rounded-circle">
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item">Olá, <?= $usuario['nome'] ?></small></a>
                <a href="" data-toggle="modal" data-target="#modaleditUser" class="dropdown-item"><i class="fa fa-user"></i> <span>Perfil</span></a>
                <a href="<?= PATH ?>admin/logout" class="dropdown-item"><i class="fa fa-power-off"></i> <span>Logout</span></a>
            </div>
        </div>
    </nav>

    <!-- Modal -->
    <div class="modal fade" id="modalQR" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary text-light">
                    <h5 class="modal-title">Gerar QRCode do cardápio</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center" id="printThis">
                    <div class="position-absolute" id="box-qrcode">
                        <div class="d-flex align-items-end" >
                            <p class="text-light text-center px-5 font-weight-bold">Acesse www.e-cardapio.com.br/web/<?= $cardapio['slug'] ?> e crie o seu agora mesmo, ou escaneie o código QR ao lado</p>
                            <img src="" id="qr" alt="">
                        </div>
                    </div>
                    <img src="<?= PATH ?>assets/admin/images/banner-qr.jpg" class="d-block w-100">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-success" onclick="printElement()"><i class="fa fa-print mr-2" aria-hidden="true"></i>Imprimir</button>
                </div>
            </div>
        </div>
    </div>