<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>eCardapio - Painel Administrativo</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= PATH ?>assets/admin/images/favicon.png" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link href="<?= PATH ?>assets/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?= PATH ?>assets/admin/css/switch.css" rel="stylesheet" type="text/css" />

    <!-- Font Awesome CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <!-- Colorpicker CSS -->
    <link href="<?= PATH ?>assets/admin/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">
    
    <!-- Fontpicker CSS -->
    <link href="<?= PATH ?>assets/admin/plugins/fontselect/fontselect-alternate.css" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link href="<?= PATH ?>assets/admin/css/style.css" rel="stylesheet" type="text/css" />

    <!-- JQuery.filer -->
    <link href="<?= PATH ?>assets/admin/plugins/jQuery.filer/jquery.filer.css" rel="stylesheet" type="text/css" />
    <link href="<?= PATH ?>assets/admin/plugins/jQuery.filer/themes/jquery.filer-dragdropbox-theme.css" rel="stylesheet" type="text/css" />

    <style>
        .parsley-error {
            border-color: #ff5d48 !important;
        }

        .parsley-errors-list.filled {
            display: block;
        }

        .parsley-errors-list {
            display: none;
            margin: 0;
            padding: 0;
        }

        .parsley-errors-list>li {
            font-size: 12px;
            list-style: none;
            color: #ff5d48;
            margin-top: 5px;
        }
    </style>
    <!-- END CSS for this page -->

</head>

<body>

    <nav class="navbar bg-primary fixed-top py-1" style="box-shadow: 0px -6px 13px 5px #000000b0;">
        <a href="<?= PATH ?>admin"><img alt="Logo" src="<?= PATH ?>assets/site/img/icon-ecardapio-white.png" width="80px" /></a>

        <?= message('message') ?>

        <a href="<?= PATH ?>cardapio" class="btn btn-outline-light my-2 my-sm-0 ml-xl-auto mr-xl-3" target="_blank" rel="noopener noreferrer" ><i class="fa fa-eye pr-xl-2" aria-hidden="true"></i><span class="d-none d-sm-inline-block">Visualizar</span></a>
        <form action="<?= PATH ?>admin/produtos/busca" method="GET" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-2 w-auto" name="produto" type="text" placeholder="Buscar produto">
            <button class="btn btn-transparent text-dark my-2 my-sm-0 btn-search" type="submit"><i class="fa fa-search pr-2" aria-hidden="true"></i></button>
        </form>

        <div class="btn-group">
            <button type="button" class="btn btn-transparent dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="<?= PATH ?>assets/admin/images/avatars/avatar7.png" width="40px" alt="Profile image" class="bg-light rounded-circle">
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item">Olá, <?= getUsername() ?></small></a>
                <a href="" data-toggle="modal" data-target="#modaleditUser" class="dropdown-item"><i class="fa fa-user"></i> <span>Perfil</span></a>
                <a href="<?= PATH ?>admin/logout" class="dropdown-item"><i class="fa fa-power-off"></i> <span>Logout</span></a>
            </div>
        </div>
        
    </nav>