<div class="content-page pt-5">
    <?php include "users/editar.phtml"; ?>
    
    <?php include "tema/index.phtml"; ?>
    <!-- Start content -->
    <div class="content" style="background-color: #1a1a1a">

        <input type="hidden" id="path" value="<?= PATH ?>">

        <div id="conteudo" class="container mt-4 mt-lg-0">
            <?php if (is_file($cardapio['imagem']) && isset($cardapio['imagem']) && $cardapio['imagem'] != "") : ?>
                <img src="<?= PATH . $cardapio['imagem'] ?>" style="height: 300px;" class="w-100 d-block rounded-lg">
            <?php else : ?>
                <div class="image-default-banner rounded-lg">
                    <span>Sem imagem de topo<br>Clique em "Trocar aparencia" e escolha uma imagem de topo</span>
                </div>
            <?php endif; ?>
            <div class="row mb-4" style="margin-top: -7rem">
                <div class="align-items-center col-xl-12 d-flex justify-content-between mt-4 pl-lg-4">
                    <span class="main-title text-light" style="font-family: <?= $tema['fonte'] ?>;"><?= $usuario['estabelecimento'] ?></span>
                    <div class="float-right pr-3">
                        <a class="btn btn-light" data-toggle="modal" href="#modalTemas"><i class="fa fa-paint-brush pr-2" aria-hidden="true"></i>Trocar Aparência</a>                       
                    </div>
                </div>
            </div>
            <!-- end row -->

            <?php foreach ($categorias as $key => $cat) : ?>
                <div class="row">
                    <div class="col-xl-12">
                        <input data-id="<?= $cat['id_categoria'] ?>" type="text" class="bg-cat-title py-3 h5 w-100 border-0 text-center nome-categoria" readonly="true" data-html="true" title="<i class='fa fa-pencil pr-2' aria-hidden='true'></i>Clique para editar o nome da categoria" data-toggle="tooltip" data-placement="top" value="<?= $cat['nome'] ?>">
                        <a href="javascript:;" class="position-absolute py-2 d-none btn-delete-cat deletar-categoria" href="#" title="Excluir categoria" onclick="remove('<?= PATH . 'admin/categorias/' . $cat['id_categoria'] . '/delete' ?>')" data-toggle="tooltip" data-placement="top"><i class="fa fa-trash fa-3x text-danger pr-2" aria-hidden="true"></i></a>
                    </div>
                </div>
                <br>
                <div class="row">
                    <?php foreach ($cat['produtos'] as $key => $value) : ?>
                        <div class="col-xl-3 col-6 pb-3 mt-3" data-html="true" title="<i class='fa fa-pencil pr-2' aria-hidden='true'></i>Clique para editar o produto" data-toggle="tooltip" data-placement="top">
                            <div class="card shadow text-left text-dark">
                                <a href="" data-toggle="modal" class="text-dark text-decoration-none" data-target="#modaleditProduct<?= $value['id_produto'] ?>">
                                    <?php if (isset($value["imagem"]) && $value["imagem"] != "") : ?>
                                        <img class="card-img-top" src="<?= thumbUrl(PATH . $value['imagem'], 260, 220) ?>">
                                    <?php else : ?>
                                        <div class="image-default-prod card-img-top">
                                        <?php if(isset($cardapio['logo']) && !empty($cardapio['logo'])): ?>
                                            <img src="<?= PATH . $cardapio['logo'] ?>" >
                                        <?php endif; ?>
                                        <span>Sem imagem</span>
                                    </div>
                                    <?php endif; ?>
                                    <div class="card-body p-2">
                                        <h5 class="card-title text-center"><?= $value['nome'] ?></h5>
                                        <p class="card-text text-center" style="min-height:63px" title="<?= $value['descricao'] ?>"><?= substr($value['descricao'], 0, 90) ?></p>
                                        <h6 class="text-center">R$<?= number_format($value['preco'], 2, ",", ".") ?></h6>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- Modal Editar produto-->
                        <?php include "produto/editar.phtml"; ?>
                    <?php endforeach; ?>
                    <div class="col-xl-3 pb-3 mt-3">
                        <div class="card text-left">
                            <div class="card-body py-4">
                                <a href="" data-toggle="modal" data-target="#modalNewProduct<?= $key ?>">
                                    <h3 class="card-title text-center text-dark">
                                        <i class="fa fa-plus fa-2x"></i><br>
                                        Adicionar produto
                                    </h3>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal Novo Produto -->
                <?php include "produto/novo.phtml"; ?>
            <?php endforeach; ?>
        </div>

        <div class="container pb-5">

            <div class="row pb-5">
                <div class="col-xl-12">
                    <a href="#" data-toggle="modal" data-target="#modalCategoria" type="text" class="btn-block bg-light btn btn-lg text-center mb-4" readonly="true" title="Clique para cadastrar uma nova categoria!" data-toggle="tooltip" data-placement="top"><i class="fa fa-plus"></i> NOVA CATEGORIA</a>
                    <?php if (count($categorias) < 1) : ?>
                        <div id="card-sem-categoria" class="jumbotron text-center" style="opacity:.9">
                            <h1 class="display-3 text-muted py-5">Bem vindo ao eCardapio!</h1>
                            <h3 class="text-muted">Você ainda não possui nenhum produto cadastrado<br>Vamos começar criando uma nova <b class="text-dark">categoria</b><br>Clique no botão de <b class="text-dark">nova categoria</b> acima</h3>
                        </div>
                    <?php endif ?>
                </div>
            </div>
            <!-- Modal Nova Categoria -->
            <?php include "categoria/novo.phtml"; ?>
            <?php include "produto/novoGenerico.phtml"; ?>
        </div>
        <!-- end row -->
        <!-- END container-fluid -->

    </div>
    <!-- END content -->

</div>
<!-- END content-page -->