
<div class="content-page pt-5">
    <?php include "users/editar.phtml"; ?>
    <!-- Start content -->
    <div class="content" style="background: url(<?= PATH . "/assets/admin/images/pattern.png" ?>);">

        <input type="hidden" id="path" value="<?= PATH ?>">

        <div id="conteudo" class="container">
            <div class="row">
                <div class="col-xl-12 mt-4 py-3">
                    <span class="main-title text-light h1"><?= $usuario['estabelecimento']?></span>
                    <a name="" id="" class="btn btn-outline-light  float-right ml-auto" href="#" role="button"><i class="fa fa-paint-brush  pr-3" aria-hidden="true"></i>Trocar Aparência</a>
                </div>
            </div>
            <!-- end row -->           

            <?php foreach ($cardapio as $key => $cat) : ?>
                <div class="row">
                    <div class="col-xl-12">
                        <input data-id="<?=$cat['id_categoria']?>" type="text" onmouseover="showSaveButton('<?= $key ?>')" onmouseout="hideSaveButton('<?= $key ?>')" class="bg-cat-title py-3 h5 w-100 border-0 text-center nome-categoria" readonly="true" data-html="true" title="<i class='fa fa-pencil pr-2' aria-hidden='true'></i>Clique para editar o nome da categoria" data-toggle="tooltip" data-placement="top" value="<?= $cat['nome'] ?>">
                        <a href="javascript:;" id="btnSaveCat<?= $key ?>" class="position-absolute px-5 py-2 d-none btn-delete-cat" href="#" title="Excluir categoria" onclick="remove('<?= PATH.'admin/categorias/'.$cat['id_categoria'].'/delete' ?>')" data-toggle="tooltip" data-placement="top"><i class="fa fa-trash fa-3x text-danger pr-2"  aria-hidden="true"></i></a>
                    </div>
                </div>
                <br>
                <div class="row">
                    <?php foreach ($cat['produtos'] as $key => $value) : ?>
                        <div class="col-xl-3 col-6 pb-3 mt-3" data-html="true" title="<i class='fa fa-pencil pr-2' aria-hidden='true'></i>Clique para editar o produto" data-toggle="tooltip" data-placement="top">
                            <div class="card shadow text-left text-dark">
                                <a href="" data-toggle="modal" class="text-dark" data-target="#modaleditProduct<?= $value['id_produto'] ?>">
                                <?php if($value["imagem"] != ""): ?>
                                    <img class="card-img-top" src="<?= thumbUrl(PATH.$value['imagem'], 260, 220) ?>">
                                <?php else: ?>
                                    <img class="card-img-top" src="https://via.placeholder.com/253x180?text=Imagem+Produto" alt="">
                                <?php endif; ?>
                                    <div class="card-body p-2">
                                        <h5 class="card-title text-center"><?= $value['nome'] ?></h5>
                                        <p class="card-text text-center" style="min-height:63px"><?= $value['descricao'] ?></p>
                                        <h6 class="text-center">R$<?= number_format($value['preco'], 2, ",", ".") ?></h6>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- Modal Editar produto-->
                       <?php include "produto/editar.phtml"; ?>
                    <?php endforeach; ?>
                    <div class="col-xl-3 pb-3">
                        <div class="card text-left">
                            <div class="card-body py-4">
                                <a href="" data-toggle="modal" data-target="#modalNewProduct<?= $key ?>">
                                    <h3 class="card-title text-center text-dark">
                                        <i class="fa fa-plus fa-2x"></i><br>
                                        Adicionar produto
                                    </h3>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal Novo Produto -->
                <?php include "produto/novo.phtml"; ?>
            <?php endforeach; ?>
        </div>

        <div class="container">

            <div class="row">
                <div class="col-xl-12">
                    <input style="cursor: pointer" data-toggle="modal" data-target="#modalCategoria" type="text" class="bg-cat-title py-3 h5 w-100 border-0 text-center" readonly="true" title="Clique para cadastrar uma nova categoria!" data-toggle="tooltip" data-placement="top" value="Nova categoria">
                </div>
            </div>
            <!-- Modal Nova Categoria -->
            <?php include "categoria/novo.phtml"; ?>
            <?php include "produto/novoGenerico.phtml"; ?>
        </div>
        <!-- end row -->
        <!-- END container-fluid -->

    </div>
    <!-- END content -->

</div>
<!-- END content-page -->