<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Área Administrativa | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="<?= PATH ?>assets/admin/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?= PATH ?>assets/admin/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="<?= PATH ?>assets/admin/css/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>Admin</b> eCardapio
      <h4 style="margin-top:0px !important">Área Administrativa</h4>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <?php if ($error != '') { ?>
        <div class="alert alert-danger">
          <?= $error ?>
        </div>
      <?php } else { ?>
        <p class="login-box-msg">Faça login para acessar o sistema</p>
      <?php } ?>
      <form action="<?= PATH ?>admin/login" method="post">
        <div class="form-group has-feedback">
          <input type="text" class="form-control" placeholder="Login" name="login">
          <span class="glyphicon glyphicon-user form-control"></span>
        </div>
        <div class="form-group has">
          <input type="password" class="form-control" placeholder="Senha" name="password">
          <span class="glyphicon glyphicon-lock form-control"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <!-- /.col -->
                <a href="<?= PATH ?>admin/forgot">Esqueci a senha</a><br>
              </label>
            </div>
          </div>
          <div class="col-xs-4 text-center">
            <button type="submit" class="btn btn-primary  btn-block btn-flat">Entrar</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- jQuery 2.2.3 -->
  <script src="<?= PATH ?>assets/admin/plugins/jQuery/jquery-2.2.3.min.js"></script>
  <!-- Bootstrap 3.3.6 -->
  <script src="<?= PATH ?>assets/admin/bootstrap/js/bootstrap.min.js"></script>
  <!-- iCheck -->
  <script src="<?= PATH ?>assets/admin/plugins/iCheck/icheck.min.js"></script>
  <script>
    $(function() {
      $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' // optional
      });
    });
  </script>
</body>

</html>