<style>
section.pricing {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFF);
}

.pricing .card {
  border: none;
  border-radius: 1rem;
  transition: all 0.2s;
  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
}

.pricing hr {
  margin: 1.5rem 0;
}

.pricing .card-title {
  margin: 0.5rem 0;
  font-size: 0.9rem;
  letter-spacing: .1rem;
  font-weight: bold;
}

.pricing .card-price {
  font-size: 3rem;
  margin: 0;
}

.pricing .card-price .period {
  font-size: 0.8rem;
}

.pricing ul li {
  margin-bottom: 1rem;
}

.pricing .text-muted {
  opacity: 0.7;
}

.pricing .btn {
  font-size: 80%;
  border-radius: 5rem;
  letter-spacing: .1rem;
  font-weight: bold;
  padding: 1rem;
  opacity: 0.7;
  transition: all 0.2s;
}

/* Hover Effects on Card */

@media (min-width: 992px) {
  .pricing .card:hover {
    margin-top: -.25rem;
    margin-bottom: .25rem;
    box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.3);
  }
  .pricing .card:hover .btn {
    opacity: 1;
  }
}
</style>

<div class="content-page pt-5">
    <section class="pricing py-5" style="background: url(<?= PATH . "/assets/admin/images/pattern2.png" ?>); background-attachment:fixed;">
        <div class="container">
            <div class="row">
                <!-- Free Tier -->
                <div class="col-lg-4">
                    <div class="card mb-5 mb-lg-0">
                    <div class="card-body">
                        <h5 class="card-title text-muted text-uppercase text-center">Grátis</h5>
                        <h6 class="card-price text-center">R$0<span class="period">/mensal</span></h6>
                        <hr>
                        <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Criação de cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Impressão do cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Customização<small><strong>(parcial)</strong></small></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Compartilhamento via QRCode</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Remoção de anúncios</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Wallpaper para cardápio</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Mais opções de layouts</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Suporte exclusivo</li>
                        </ul>
                        <button data-url="<?= PATH ?>admin/planos/update" <?=($usuario['flag_assinante'] == 2)?"disabled":""?> class="btn btn-block btn-primary text-uppercase assinar-plano"><?=($usuario['flag_assinante'] == 2)?"Você já é um assinante":"Assinar"?></button>
                    </div>
                    </div>
                </div>
                <!-- Plus Tier -->
                <div class="col-lg-4">
                    <div class="card mb-5 mb-lg-0">
                    <div class="card-body">
                        <h5 class="card-title text-muted text-uppercase text-center">Plus</h5>
                        <h6 class="card-price text-center">R$9<span class="period">/mensal</span></h6>
                        <hr>
                        <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Criação de cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Impressão do cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Customização<small><strong>(parcial)</strong></small></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Compartilhamento via QRCode</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Remoção de anúncios</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Wallpaper para cardápio</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Mais opções de layouts</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Suporte exclusivo</li>
                        </ul>
                        <button data-url="<?= PATH ?>admin/planos/update" <?=($usuario['flag_assinante'] == 2)?"disabled":""?> class="btn btn-block btn-primary text-uppercase assinar-plano"><?=($usuario['flag_assinante'] == 2)?"Você já é um assinante":"Assinar"?></button>
                    </div>
                    </div>
                </div>
                <!-- Pro Tier -->
                <div class="col-lg-4">
                    <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-muted text-uppercase text-center">Pro</h5>
                        <h6 class="card-price text-center">R$49<span class="period">/mensal</span></h6>
                        <hr>
                        <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fa fa-check"></i></span><strong>Criação de cardápio</strong></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Impressão do cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Customização<small><strong>(parcial)</strong></small></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Compartilhamento via QRCode</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Remoção de anúncios</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Wallpaper para cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Mais opções de layouts</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Suporte exclusivo</li>
                        </ul>
                        <button data-url="<?= PATH ?>admin/planos/update" <?=($usuario['flag_assinante'] == 2)?"disabled":""?> class="btn btn-block btn-primary text-uppercase assinar-plano"><?=($usuario['flag_assinante'] == 2)?"Você já é um assinante":"Assinar"?></button>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>