<div class="back-to-top-wrapper no-print">
    <a href="<?= PATH ?>" class="back-to-top-link btn btn-link rounded-pill bg-transparent" title="Crie o seu cardápio agora mesmo!" data-toggle="tooltip">
        Cardápio criado com <img src="<?= PATH ?>assets/admin/images/icon-ecardapio-text.png" width="129px"></a>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="<?= PATH ?>assets/admin/plugins/dom-to-image/dom-to-image.js"></script>
<script>
    $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();
    })

    function downloadImg(slug) {
        $("div").remove(".no-print");
        document.getElementById("overlay").style.display = "block";
        var el = document.getElementById('conteudo-cardapio');
        domtoimage.toJpeg(el, {
                quality: 0.95
            })
            .then(function(dataUrl) {
                document.getElementById("overlay").style.display = "none";
                var link = document.createElement('a');
                link.download = slug + '.jpeg';
                link.href = dataUrl;
                link.click();
            });
    }
</script>
<!-- parsley -->
<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/parsley.min.js"></script>
<script src="<?= PATH ?>assets/admin/plugins/parsleyjs/pt-br.js"></script>
<script src="<?= PATH ?>assets/site/js/smooth-scroll.js"></script>
</body>

</html>