<!doctype html>
<html lang="pt-br">

<head>
    <title><?= $usuario['estabelecimento'] ?> - eCardapio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=<?= $tema['fonte'] ?>" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <!-- Bootstrap CSS -->
    <link href="<?= PATH ?>assets/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="<?= PATH ?>assets/site/jquery/jquery-3.4.1.min.js"></script>
    <style>
        .bg-header {
            background: url(<?= PATH . $tema['imagem'] ?>);
            background-size: cover;
            background-position: right;
            background-repeat: no-repeat;
        }

        .title-header {
            font-size: 80px;
            font-family: <?= $tema['fonte'] ?>;
            line-height: 1;
            text-shadow: 1px 4px 3px #171717;
        }

        .bg-fundo {
            background-color: <?= $tema['cor_secundaria'] ?>;
        }

        .bg-primaria {
            background-color: <?= $tema['cor_primaria'] ?>;
        }

        .text-claro {
            color: <?= $tema['texto_claro'] ?>;
        }

        .text-escuro {
            color: <?= $tema['texto_escuro'] ?>;
        }
        @media only and (min-width: 320px){
            .img-logo{
                width: 50%;
            }
        }
        
    </style>
</head>

<body>

    <div class="container-fluid bg-fundo" <?= (isset($fundo)) ? 'style="background: url(' . PATH . $fundo . '); background-attachment:fixed;"' : '' ?>>
        <div class="row">
            <div class="col-xl-12 px-0">
                <img src="<?= PATH . $tema['imagem'] ?>" class="img-fluid w-100 d-block shadow">
            </div>
        </div>
        <div class="row bg-dark">
            <div class="container">
                <div class="row" style="margin-top: -5rem;">
                    <div class="col-xl-2 text-center">
                        <img src="<?= PATH . $logo ?>" class="bg-light img-fluid img-logo p-1 rounded-circle">
                    </div>
                    <div class="col-xl py-4">
                        <div class=" title-header text-claro mt-n4 mb-4"><?= $usuario['estabelecimento'] ?></div>
                        <div class="d-flex flex-wrap justify-content-around">
                            <div class="d-flex align-items-center">
                                <i class="fa fa-whatsapp fa-3x text-light mr-3" aria-hidden="true"></i>
                                <strong class="text-light h3"><?= $usuario['whatsapp'] ?></strong>
                            </div>
                            <?php if($usuario['flag_wifi'] == 1): ?>
                            <div class="d-flex align-items-center">
                                <i class="fa fa-wifi text-light fa-2x mr-2" aria-hidden="true"></i>
                                <span class="text-light">Wi-fi grátis</span>
                            </div>
                            <?php endif; ?>
                            <?php if($usuario['flag_cartao'] == 1): ?>
                                <div class="d-flex align-items-center">
                                    <i class="fa fa-credit-card text-light fa-2x mr-2" aria-hidden="true"></i>
                                    <span class="text-light">Aceita cartão crédito</span>
                                </div>
                            <?php endif; ?>
                            <?php if($usuario['facebook'] != ""): ?>
                                <a href="<?= $usuario['facebook'] ?>" target="_blank" role="button" class="d-flex align-items-center">
                                    <i class="fa fa-facebook-square text-light fa-2x mr-2" aria-hidden="true"></i>
                                    <span class="text-light">Facebook</span>
                                </a>
                            <?php endif; ?>
                            <?php if($usuario['instagram'] != ""): ?>
                                <a href="<?= $usuario['instagram'] ?>" target="_blank" role="button" class="d-flex align-items-center">
                                    <i class="fa fa-instagram text-light fa-2x mr-2" aria-hidden="true"></i>
                                    <span class="text-light">Instagram</span>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>