<!doctype html>
<html lang="pt-br">

<head>
    <title><?= $usuario['estabelecimento'] ?> - eCardapio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=<?= $tema['fonte'] ?>" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    

    <!-- Bootstrap CSS -->
    <link href="<?= PATH ?>assets/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="<?= PATH ?>assets/site/jquery/jquery-3.4.1.min.js"></script>
</head>
<body>

    <div class="container-fluid bg-fundo" <?= (isset($fundo))?'style="background: url('.PATH .$fundo.'); background-attachment:fixed;"':''?>>
        <div class="row bg-header py-5">
            <div class="col-xl-12 text-center py-4">
                <div class=" title-header text-claro"><?= $usuario['estabelecimento'] ?></div>
                <div class="d-flex flex-row align-items-center justify-content-center pt-4">
                    <i class="fa fa-whatsapp fa-3x text-success mr-3" aria-hidden="true"></i>
                    <strong class="text-light h3"><?= $usuario['whatsapp'] ?></strong>
                </div>               
            </div>            
        </div>

