<style>
    .bg-fundo {
        background-color: <?= $tema['cor_secundaria'] ?>;
    }

    .text-title {
        color: <?= $tema['cor_primaria'] ?>;
        font-weight: bold;
        font-size: 16pt;
        padding-bottom: 5px;
    }

    .linewrapper {
        display: flex;
        align-items: baseline;
    }

    .middle {
        border-bottom: 1px dotted #000;
        flex-grow: 1;
        margin: 0 5px;
    }

    .ingredients {
        margin-top: -0.5rem;
        font-weight: bold;
        font-size: 10pt;
    }

    .title-header {
        font-size: 80px;
        font-family: <?= $tema['fonte'] ?>;
        line-height: 1;
    }

    .card {
        background-color: unset !important;
    }

    @media (min-width: 576px) {
        .card-columns {
            column-count: 1;
        }
    }

    .text-claro {
        color: <?= $tema['texto_claro'] ?>
    }

    .text-escuro {
        color: <?= $tema['texto_escuro'] ?>
    }
    .image-default-banner {
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        align-items: center;
        width: 100%;
        height: 150px;
        background-color: #cccccc;
    }

    .image-default-banner>img {
        width: 100px;
        filter: grayscale();
        opacity: .5;
        padding-bottom: .5rem;
    }

    .image-default-banner span {
        color: #808080;
        text-align: center;
    }
</style>

<div class="container" style="min-height: 400px;">
    <div class="row">
        <div class="card-columns w-100 mt-4 px-lg-4">
            <?php foreach ($cardapio as $key => $val) : ?>
                <?php if ($key == 1) : ?>
                    <div class="mx-auto pb-4 text-center">
                        <a href="#">
                            <img src="<?= PATH ?>assets/site/img/anuncios/prats.jpg" class="img-fluid">
                        </a>
                    </div>
                <?php elseif ($key > 1) : ?>
                    <div class="image-default-banner px-2 mb-4 mt-2">
                        <div class="d-block">
                            <span><i class="fa fa-bullhorn fa-4x" aria-hidden="true"></i></span>
                        </div>
                        <div class="d-block">
                            <span class="h4 d-block">ANUNCIE AQUI</span>
                            <span>Espaço reservado para anúncios publicitários, anunciantes entre em contato com contato@ecardapio.com.br</span>
                        </div>
                        <div class="d-block">
                            <span><i class="fa fa-bullhorn fa-4x fa-flip-horizontal" aria-hidden="true"></i></span>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="card">
                    <div class="text-center py-3 bg-primaria">
                        <h2 class="text-light pl-4"><b><?= $val['nome'] ?></b></h2>
                    </div>
                    <div class="bg-light pt-2 px-lg-4 px-2">
                        <?php foreach ($val['produtos'] as $key => $value) : ?>
                            <div class="pb-2">
                                <div class="linewrapper">
                                    <span class="text-title"><?= $value['nome'] ?></span>
                                    <div class="middle"></div>
                                    <span class="text-title">R$ <?= number_format($value['preco'], 2, ",", ".") ?></span>
                                </div>
                                <div class="ingredients"><?= $value['descricao'] ?></div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <?php if(!empty($usuario['rua']) && !empty($usuario['bairro']) && !empty($usuario['cidade'])): ?>
            <div class="card">
                <div class="bg-primaria py-3">
                    <h2 class="text-light pl-4"><b>Onde estamos</b></h2>
                </div>
                <div class="bg-light py-2 px-4">
                    <h5 class="pl-4 pb-2 text-center">Horário de atendimento: <?= $usuario['horario'] ?></h5>
                    <iframe src="https://www.google.com.br/maps?q='<?= $usuario['rua'] . ", " . $usuario['bairro'] . ", " . $usuario['cidade'] ?>',&output=embed" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    <h5 class="text-center pt-2"><?= $usuario['rua'] ?><br><?= $usuario['bairro'] ?></h5>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>