<style>
    .bg-header {
        background: url(<?= $tema['imagem'] ?>);
        background-size: cover;
        background-position: right;
        background-repeat: no-repeat;
    }

    .bg-title {
        background: linear-gradient(-3deg, #f8f9fa 28%, <?= $tema['cor_primaria'] ?> 31%);
    }

    .bg-fundo {
        background-color: <?= $tema['cor_secundaria'] ?>;
    }

    .text-title {
        color: <?= $tema['cor_primaria'] ?>;
        font-weight: bold;
        font-size: 20pt;
    }

    .linewrapper {
        display: flex;
        align-items: baseline;
    }

    .middle {
        border-bottom: 1px dotted #000;
        flex-grow: 1;
        margin: 0 5px;
    }

    .ingredients {
        margin-top: -0.5rem;
        font-weight: bold;
        font-size: 10pt;
    }

    .title-header {
        font-size: 80px;
        font-family: <?= $tema['fonte'] ?>;
        line-height: 1;
    }

    .card {
        background-color: unset !important;
    }

    @media (min-width: 576px) {
        .card-columns {
            column-count: 1;
        }
    }

    .text-claro {
        color: <?= $tema['texto_claro'] ?>
    }

    .text-escuro {
        color: <?= $tema['texto_escuro'] ?>
    }
</style>

    <div class="container">
        <div class="row">
            <div class="card-columns mt-4 px-4">
                <?php foreach ($cardapio as $key => $val) : ?>
                    <div class="card">
                        <div class="text-center py-3">
                            <h2 class="text-light pl-4"><b><?= $val['nome'] ?></b></h2>
                        </div>
                        <div class="bg-light pt-2 px-4">
                            <?php foreach ($val['produtos'] as $key => $value) : ?>
                                <div class="pb-2">
                                    <div class="linewrapper">
                                        <span class="text-title"><?= $value['nome'] ?></span>
                                        <div class="middle"></div>
                                        <span class="text-title">R$ <?= number_format($value['preco'], 2, ",", ".") ?></span>
                                    </div>
                                    <div class="ingredients"><?= $value['descricao'] ?></div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                <div class="card">
                    <div class="bg-title py-3">
                        <h2 class="text-light pl-4"><b>Onde estamos</b></h2>
                    </div>
                    <div class="bg-light py-2 px-4">
                        <h5 class="pl-4 pb-2 text-center">Horário de atendimento: <?= $usuario['horario'] ?></h5>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1012.4944726844747!2d-54.57527582428262!3d-25.4511598767081!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94f69b0544337e57%3A0xa72aae348c6ca711!2sRua%20C%2C%20937%2C%20PR%2C%20Brasil!5e0!3m2!1spt-BR!2sbr!4v1590088419578!5m2!1spt-BR!2sbr" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        <h5 class="text-center pt-2"><?= $usuario['rua'] ?><br><?= $usuario['bairro'] ?></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>