<style>
    .bg-header {
        background: url(<?= $tema['imagem'] ?>);
        background-size: cover;
        background-position: right;
        background-repeat: no-repeat;
    }

    .title-header {
        font-size: 80px;
        font-family: <?= $tema['fonte'] ?>;
        line-height: 1;
    }

    .bg-fundo {
        background-color: <?= $tema['cor_secundaria'] ?>;
    }

    .bg-primaria {
        background-color: <?= $tema['cor_primaria'] ?>;
    }

    .text-claro {
        color: <?= $tema['texto_claro'] ?>
    }

    .text-escuro {
        color: <?= $tema['texto_escuro'] ?>
    }

    .fontstar {
        padding-left: 0px;

    }
</style>

<body>

    <div class="container-fluid bg-fundo" style="background: url(<?= PATH . "/assets/admin/images/pattern2.png" ?>); background-attachment:fixed;">
        <div class="row bg-header py-5">
            <div class="col-xl-6 text-center py-4">
                <div class="pl-5 title-header text-claro"><?= $usuario['estabelecimento'] ?></div>
                <img src="https://i2.wp.com/multarte.com.br/wp-content/uploads/2018/10/logo-whatsapp-png-transparente17.png?fit=1024%2C727&ssl=1" class="pb-2" width="80px" alt="">
                <div class="d-inline-block pt-4 text-light h3"><b><?= $usuario['whatsapp'] ?></b></div>
            </div>
            <div class="col-xl-6">
            </div>
        </div>
        <div class="container">
            <?php foreach ($cardapio as $key => $val) : ?>
                <div class="row" id="cat-<?= $val['id_categoria'] ?>">
                    <div class="col-12">
                        <div class="text-center py-4">
                            <div class="dropdown open">
                                <a class="dropdown-toggle text-light h3" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?= $val['nome'] ?></a>
                                <div class="dropdown-menu dropdown-menu-center bg-dark ">
                                    <?php foreach ($cardapio as $key => $value) : ?>
                                        <a class="dropdown-item text-light" href="#cat-<?= $value['id_categoria'] ?>"><?= $value['nome'] ?></a>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <?php foreach ($val['produtos'] as $key => $value) : ?>
                        <div class="col-xl-3 pb-4">
                            <!-- Button trigger modal -->
                            <a href="#" class="text-decoration-none" data-toggle="modal" data-target="#modalAvaliacao<?= $key ?>">
                                <div class=" text-center">
                                    <?php if ($value["imagem"] != "") : ?>
                                        <img class="card-img-top" src="<?= thumbUrl(PATH . $value['imagem'], 260, 220) ?>">
                                    <?php else : ?>
                                        <img class="card-img-top" src="<?= PATH ?>uploads/produto/253x180.png" alt="">
                                    <?php endif; ?>
                                    <div class="card-body bg-primaria text-claro">
                                        <h5 class="card-title"><?= $value['nome'] ?></h5>
                                        <?php for ($i = 0; $i < 5; $i++) : ?>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                        <?php endfor; ?>
                                        <br>
                                        <p class="card-text pt-2"><?= $value['descricao'] ?></p>
                                    </div>
                                    <div class="card-footer bg-primaria text-claro border-top-0">
                                        <h5 class="text-claro">R$<?= number_format($value['preco'], 2, ",", ".") ?></h5>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="modalAvaliacao<?= $key ?>" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header bg-primaria text-claro">
                                        <h5 class="modal-title"><?= $value['nome'] ?></h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <?php if ($value["imagem"] != "") : ?>
                                            <img class="card-img-top" src="<?= PATH . $value['imagem'] ?>">
                                        <?php else : ?>
                                            <img class="card-img-top" src="https://via.placeholder.com/253x180?text=Imagem+Produto" alt="">
                                        <?php endif; ?>
                                        <div class="card-body ">
                                            <h3 class="card-title"><?= $value['nome'] ?></h3>
    
                                            <p class="card-text"><?= $value['descricao'] ?></p>
                                            <hr>
                                            <h4 class="card-title">Avaliação</h4>
    
                                            <form action="<?= PATH . "admin/produtos/avaliar/" . $value['id_produto'] ?>" method="post">
                                                <div class="form-group">
                                                    <label>Nome</label>
                                                    <input type="text" class="form-control" name="nome" placeholder="Digite seu nome" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Comentário</label>
                                                    <textarea class="form-control" name="comentario" id="" rows="3"></textarea>
                                                </div>
                                                <div class="form-group">
                                                    <label>Avaliação</label>
                                                    <select name="nota" class="star">
                                                        <option value="">--</option>
                                                        <option value="1">1</option>
                                                        <option value="2">2</option>
                                                        <option value="3">3</option>
                                                        <option value="4" selected>4</option>
                                                        <option value="5">5</option>
                                                    </select>
                                                </div><br>
                                                <button type="submit" class="btn btn-primary">Enviar</button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="bg-title py-3">
                            <h2 class="text-center pl-4"><b>Onde estamos</b></h2>
                        </div>
                        <div class="bg-light py-2 px-4">
                            <h5 class="pl-4 pb-2 text-center">Horário de atendimento: <?= $usuario['horario'] ?></h5>
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1012.4944726844747!2d-54.57527582428262!3d-25.4511598767081!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94f69b0544337e57%3A0xa72aae348c6ca711!2sRua%20C%2C%20937%2C%20PR%2C%20Brasil!5e0!3m2!1spt-BR!2sbr!4v1590088419578!5m2!1spt-BR!2sbr" width="100%" height="400" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                            <h5 class="text-center pt-2"><?= $usuario['rua'] ?><br><?= $usuario['bairro'] ?></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>