 <div class="modal fade custom-modal" id="modaleditProduct<?= $value['id_produto'] ?>" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered" role="document">
         <div class="modal-content">
             <div class="modal-header bg-primary text-light">
                 <h5 class="modal-title"><?= $value['nome'] ?></h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true">&times;</span>
                 </button>
             </div>
             <form action="<?= PATH . "admin/produtos/" . $value['id_produto'] ?>" method="POST" enctype="multipart/form-data">
                 <div class="modal-body">
                     <div class="container-fluid">
                         <input type="hidden" name="id_categoria" value="<?= $cat['id_categoria'] ?>">
                         <input type="hidden" name="imagem" value="<?= $value['imagem'] ?>">
                         <div class="form-group">
                             <label for="input_file">Imagem</label>
                             <input type="file" name="imagem-produto" data-jfiler-limit="1" accept="image/*">
                         </div>
                         <div class="form-group">
                             <label for="prod-nome">Nome</label>
                             <input type="text" class="form-control" name="nome" value="<?= $value['nome'] ?>" placeholder="">
                         </div>
                         <div class="form-group">
                             <label for="">Descrição</label>
                             <textarea class="form-control" name="descricao" rows="3"><?= $value['descricao'] ?></textarea>
                         </div>
                         <div class="form-row">
                             <div class="col-xl-6">
                                 <label for="prod-preco">Preço(R$)</label>
                                 <input type="number" min="0.00" step="0.01" value="<?= $value['preco'] ?>" class="form-control" name="preco" placeholder="">
                             </div>
                             <div class="col-xl-6">
                                 <label for="prod-ativo">Ativo</label>
                                 <select name="ativo" class="form-control">
                                    <option value="1" <?= ($value['ativo'] == 1)?"selected":"" ?>>SIM</option>
                                    <option value="0" <?= ($value['ativo'] == 0)?"selected":"" ?>>NÃO</option>
                                </select>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="modal-footer">
                     <a href="javascript:;" onclick="remove('<?= PATH . '/admin/produtos/' . $value['id_produto'] . '/delete' ?>')" class="btn btn-danger mr-auto text-light"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</a>
                     <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                     <button type="submit" class="btn btn-success">Salvar</button>
                 </div>
             </form>
         </div>
     </div>
 </div>