<div class="modal fade custom-modal" id="modalNewProductGeneric" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-light">
                <h5 class="modal-title" id="titulo-produto">Novo produto da categoria </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= PATH ?>admin/produtos/create" method="POST" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="container-fluid">
                        <input id="id-categoria-generico" type="hidden" name="id_categoria" value="">
                        <div class="form-group">
                            <label for="prod-nome">Imagem</label>
                            <input type="file" name="imagem-produto" data-jfiler-limit="1">                           
                        </div>
                        <div class="form-group">
                            <label for="prod-nome">Nome</label>
                            <input type="text" class="form-control" name="nome" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="">Descrição</label>
                            <textarea class="form-control" name="descricao" rows="3"></textarea>
                        </div>
                        <div class="form-row">
                            <div class="col-xl-6">
                                <label for="prod-preco">Preço(R$)</label>
                                <input type="number" min="0.00" step="0.01" value="0.00" class="form-control" name="preco" placeholder="">
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>