<div class="modal fade custom-modal" id="modalNewProduct<?= $key ?>" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-light">
                <h5 class="modal-title">Novo produto da categoria <?= $cat['nome'] ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= PATH ?>admin/produtos/create" method="POST" enctype="multipart/form-data" data-parsley-validate novalidate>
                <div class="modal-body">
                    <div class="container-fluid">
                        <input type="hidden" name="id_categoria" value="<?= $cat['id_categoria'] ?>">
                        <div class="form-group">
                            <label for="prod-nome">Imagem</label>
                            <input type="file" name="imagem-produto" class="file-input" data-jfiler-limit="1" accept="image/*">                           
                        </div>
                        <div class="form-group">
                            <label for="prod-nome">Nome</label>
                            <input id="nome1" type="text" class="form-control" name="nome" placeholder="Escreva o nome do produto" parsley-trigger="change" required >
                        </div>
                        <div class="form-group">
                            <label for="">Descrição/Ingredientes</label>
                            <textarea id="descricao1" class="form-control" name="descricao" rows="3"></textarea>
                        </div>
                        <div class="form-row">
                            <div class="col-xl-6">
                                <label for="prod-preco">Preço(R$)</label>
                                <input id="preco1" type="text" class="form-control preco-produto-cadastro" name="preco" parsley-trigger="change" required placeholder="0,00">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success salvar-produto1"><i class="fa fa-floppy-o pr-1" aria-hidden="true"></i>Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>