<style>
    .edit {
        display: none;
    }

    .card-title:hover {
        cursor: pointer;
    }

    .card-title:hover .edit {
        display: inline-block;
        color:royalblue;
    }
</style>
<div class="content-page">

    <!-- Start content -->
    <div class="content" style="background: url(<?= PATH . "/assets/admin/images/pattern.png" ?>);height: 650px;background-repeat: repeat-y;background-size:cover;">

        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-12">
                    <div class="breadcrumb-holder">
                        <h1 class="main-title float-left">Cardapio</h1>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-produto">Home</li>/
                            <li class="breadcrumb-produto active">Produtos</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- end row -->

            <?= message('message') ?>

            <?php foreach($categorias as $key => $value): ?>
                <div class="row" style="text-align: center">
                    <h4 class="col-md-12"><b><?=$value['nome']?></b></h4>
                </div>
            <?php endforeach; ?>
            <div class="row" style="text-align: center">
                <h4 data-toggle="modal" data-target="#modalCategoria" style="cursor: pointer" class="col-md-12"><b>Nova categoria +</b></h4>
            </div>

            <div class="row">
                <?php foreach ($data as $key => $value) : ?>
                    <div class="col-xl-3 pb-3">
                        <div class="card shadow text-left">
                            <img class="card-img-top" src="holder.js/100px180/" alt="">
                            <div class="card-body">
                                <h5 class="card-title text-center"><?= $value['nome'] ?>
                                    <span class="edit" title="Editar nome" data-toggle="tooltip" data-placement="top"><i class="fa fa-pencil"></i></span>
                                </h5>
                                <p class="card-text text-center" style="min-height:63px" contenteditable="false"><?= $value['descricao'] ?></p>
                                <h6 class="text-center" contenteditable="false">R$<?= $value['preco'] ?></h6>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <div class="col-xl-3 pb-3">
                    <div class="card text-left">                        
                        <div class="card-body py-4">
                        <a href="" data-toggle="modal" data-target="#modelId">
                            <h3 class="card-title text-center text-dark">
                                <i class="fa fa-plus fa-2x"></i><br>
                                Adicionar produto
                            </h3>                            
                        </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal Categoria -->
            <div class="modal fade custom-modal" id="modalCategoria" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <form id="form-categoria" role="form" method="post" action="<?= PATH ?>admin/categorias/create" enctype="multipart/form-data" data-parsley-validate novalidate>
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal_add_user">Adicionar nova categoria</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="input_file">Imagem</label>
                                            <input type="file" name="imagem-categoria" id="imagem-categoria" data-jfiler-limit="1">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="desperson">Nome*</label>
                                            <input type="text" id="desperson" name="nome" class="form-control" parsley-trigger="change" required />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Ativo</label>
                                            <select name="ativo" class="form-control">
                                                <option value="1">SIM</option>
                                                <option value="0">NÃO</option>
                                            </select> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button id="salvar-categoria" type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                        </form>  
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade custom-modal" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                            <div class="modal-header">
                                    <h5 class="modal-title">Novo produto</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                </div>
                        <div class="modal-body">
                            <div class="container-fluid">
                                <form action="" id="formNewProd">
                                    <div class="form-group">
                                    <label for="idcat">Categoria</label>
                                        <select class="custom-select" name="id_categoria" id="idcat">
                                            <option selected>Selecione a categoria</option>
                                            <?php foreach($categorias as $key => $value): ?>
                                                <option value="<?= $value['id_categoria'] ?>"><?= $value['nome'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                      <label for="prod-nome">Nome</label>
                                      <input type="text" class="form-control" name="nome" id="prod-nome" placeholder="">
                                    </div>                                   
                                    <div class="form-group">
                                      <label for="">Descrição</label>
                                      <textarea class="form-control" name="desc" id="prod-desc" rows="3"></textarea>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- end row -->

        </div>
        <!-- END container-fluid -->

    </div>
    <!-- END content -->

</div>
<!-- END content-page -->