 <!-- Footer -->
 <div class="text-center bg-dark pt-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-12 p-3">
          <h2 class="mb-4">Contact</h2>
          <p class="m-0">
            <a href="tel:+246 - 542 550 5462" class="text-white">+246 - 542 550 5462</a>
          </p>
          <p>
            <a href="mailto:info@pingendo.com" class="text-white">info@pingendo.com</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-muted">© Copyright 2018 Pingendo - All rights reserved. </p>
        </div>
      </div>
    </div>
  </div>
  <!-- JavaScript dependencies -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="<?= PATH ?>assets/site/js/smooth-scroll.js"></script>
  <!-- parsley -->
  <script src="<?= PATH ?>assets/admin/plugins/parsleyjs/parsley.min.js"></script>
  <script src="<?= PATH ?>assets/admin/plugins/parsleyjs/pt-br.js"></script>

  <script src="<?= PATH ?>assets/site/js/cardapio.js"></script>

  <!--sweet alert-->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

  </script>

</body>

</html>