<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>eCardapio - Cardapio Digital</title>
  <meta name="description">
  <meta name="keywords">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="<?= PATH ?>assets/site/css/flat.css" type="text/css">
  <!-- Script: Make my navbar transparent when the document is scrolled to top -->
  <script src="<?= PATH ?>assets/site/js/navbar-ontop.js"></script>
  <!-- Script: Animated entrance -->
  <script src="<?= PATH ?>assets/site/js/animate-in.js"></script>

  <style>
        .parsley-error {
            border-color: #ff5d48 !important;
        }

        .parsley-errors-list.filled {
            display: block;
        }

        .parsley-errors-list {
            display: none;
            margin: 0;
            padding: 0;
        }

        .parsley-errors-list>li {
            font-size: 12px;
            list-style: none;
            color: #ff5d48;
            margin-top: 5px;
        }
    </style>
    <!-- END CSS for this page -->
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md bg-primary navbar-light fixed-top py-1">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar3SupportedContent" aria-controls="navbar3SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row">
        <div class="col-md-12"><a class="navbar-brand" href="<?= PATH ?>"><img src="<?= PATH ?>assets/site/img/icon-ecardapio-white.png" class="d-inline-block align-top" alt="" width="90"></a></div>
      </div>
      <div class="collapse navbar-collapse text-center justify-content-center" id="navbar3SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item mx-2">
            <a class="nav-link" href="<?= PATH ?>">
              <b class="text-light">HOME</b>
            </a>
          </li>
          <li class="nav-item mx-2 text-light">
            <a class="nav-link text-light" href="#menu">SOBRE</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link text-light" href="#venue">CONTATO</a>
          </li>
        </ul>
        <a class="btn navbar-btn btn-outline-light mx-2" href="#book">Entrar</a>
      </div>
    </div>
  </nav>