 <div class="modal fade custom-modal" id="modaleditUser" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
         <div class="modal-content">
             <div class="modal-header bg-primary text-light">
                 <h5 class="modal-title">Dados do usuário</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true">&times;</span>
                 </button>
             </div>
             <form id="form-editar-usuario" role="form" method="post" action="<?= PATH ?>admin/users/update" enctype="multipart/form-data" data-parsley-validate novalidate>
                 <div class="modal-body">
                     <div class="container">
                         <div class="row">

                            <input type="hidden" name="id_usuario" value="<?=$usuario['id_usuario']?>">
    
                             <div class="col-lg-9 col-xl-9">

                                 <h4>Dados pessoais:</h4><hr>
    
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Nome completo</label>
                                             <input class="form-control" name="nome" type="text" value="<?=$usuario['nome']?>" required />
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Email</label>
                                             <input class="form-control" name="email" type="email" value="<?=$usuario['email']?>" required />
                                         </div>
                                     </div>
                                 </div>

                                 <h4>Dados da Empresa:</h4><hr>
    
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Estabelecimento</label>
                                             <input class="form-control" name="estabelecimento" type="text" value="<?=$usuario['estabelecimento']?>" required/>
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Horário de atendimento</label>
                                             <input id="altera-horario" class="form-control" name="horario" type="text" value="<?=$usuario['horario']?>" required/>
                                         </div>
                                     </div>
                                 </div>

                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Categoria Estabelecimento</label>
                                             <input class="form-control" name="categoria" type="text" value="<?=$usuario['categoria']?>"/>
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Cidade</label>
                                             <input class="form-control" name="cidade" type="text" value="<?=$usuario['cidade']?>" required/>
                                         </div>
                                     </div>
                                 </div>

                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Rua</label>
                                             <input class="form-control" name="rua" type="text" value="<?=$usuario['rua']?>" required/>
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Bairro</label>
                                             <input class="form-control" name="bairro" type="text" value="<?=$usuario['bairro']?>" required/>
                                         </div>
                                     </div>
                                 </div>

                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Número</label>
                                            <input class="form-control" name="numero" type="text" value="<?=$usuario['numero']?>" required/>
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Telefone</label>
                                            <input id="altera-telefone" class="form-control" name="telefone" type="text" value="<?=$usuario['telefone']?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Whatsapp</label>
                                            <input id="altera-whats" class="form-control" name="whatsapp" type="text" value="<?=$usuario['whatsapp']?>" />
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Facebook</label>
                                            <input class="form-control" name="facebook" type="text" value="<?=$usuario['facebook']?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Instagram</label>
                                            <input class="form-control" name="instagram" type="text" value="<?=$usuario['instagram']?>" />
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label>Sobre</label>
                                            <textarea name="sobre" class="form-control" rows="4"><?=$usuario['sobre']?></textarea>
                                        </div>
                                    </div>
                                </div>

                                <a href="<?= PATH ?>admin/planos">planos</a>
    
                             </div>
    
    
    
                             <div class="col-lg-3 col-xl-3 border-left">
    
                                 <div class="m-b-10"></div>
    
                                 <div id="avatar_image">
                                     <img style="max-width:100px; height:auto;" src="<?= PATH ?>assets/admin/images/avatars/avatar7.png" />
                                     <br />
                                     <i class="fa fa-trash-o fa-fw"></i> <a class="delete_image" href="#">Remover avatar</a>
    
                                 </div>
                                 <div id="image_deleted_text"></div>
    
    
                                 <div class="m-b-10"></div>
    
                                 <div class="form-group">
                                     <label>Alterar avatar</label>
                                     <input type="file" name="image" class="form-control">
                                 </div>
    
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="modal-footer">
                     <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                     <button type="submit" class="btn btn-success">Salvar</button>
                 </div>
             </form>
         </div>
     </div>
 </div>