 <div class="modal fade custom-modal" id="modaleditUser" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
         <div class="modal-content">
             <div class="modal-header bg-primary text-light">
                 <h5 class="modal-title">Dados do usuário</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true">&times;</span>
                 </button>
             </div>
             <form action="#" method="post" enctype="multipart/form-data">
                 <div class="modal-body">
                     <div class="container">
                         <div class="row">
    
                             <div class="col-lg-9 col-xl-9">
    
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Nome completo (obrigatório)</label>
                                             <input class="form-control" name="name" type="text" value="Administrator" required />
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Email (obrigatório)</label>
                                             <input class="form-control" name="email" type="email" value="office@website.com" required />
                                         </div>
                                     </div>
                                 </div>
    
                                 <div class="row">
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Senha</label>
                                             <input class="form-control" name="password" type="password" value="" />
                                         </div>
                                     </div>
    
                                     <div class="col-lg-6">
                                         <div class="form-group">
                                             <label>Skype</label>
                                             <input class="form-control" name="skype" type="text" value="skypeid" />
                                         </div>
                                     </div>
                                 </div>
    
                             </div>
    
    
    
                             <div class="col-lg-3 col-xl-3 border-left">
                                 <b>Ultima atividade</b>: Dec 06 2017, 22:23
                                 <br />
                                 <b>Data de cadastro: </b>: Nov 24 2017, 20:32
                                 <br />
                                 <b>IP registrado: </b>: 123.456.789
    
                                 <div class="m-b-10"></div>
    
                                 <div id="avatar_image">
                                     <img style="max-width:100px; height:auto;" src="<?= PATH ?>assets/admin/images/avatars/avatar7.png" />
                                     <br />
                                     <i class="fa fa-trash-o fa-fw"></i> <a class="delete_image" href="#">Remover avatar</a>
    
                                 </div>
                                 <div id="image_deleted_text"></div>
    
    
                                 <div class="m-b-10"></div>
    
                                 <div class="form-group">
                                     <label>Alterar avatar</label>
                                     <input type="file" name="image" class="form-control">
                                 </div>
    
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="modal-footer">
                     <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                     <button type="submit" class="btn btn-success">Salvar</button>
                 </div>
             </form>
         </div>
     </div>
 </div>