<div class="content-page">

	<!-- Start content -->
	<div class="content">

		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-12">
					<div class="breadcrumb-holder">
						<h1 class="main-title float-left">Usuários</h1>
						<ol class="breadcrumb float-right">
							<li class="breadcrumb-item">Home</li>
							<li class="breadcrumb-item active">Usuários</li>
						</ol>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<!-- end row -->

			<?= message('message') ?>
		
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
					<div class="card mb-3">
						<div class="card-header">
							<span class="pull-right">							
								<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_add_user">
									<i class="fa fa-user-plus" aria-hidden="true"></i> Adicionar novos usuários
								</button>							
							</span>
							<div class="modal custom-modal" tabindex="-1" role="dialog" aria-labelledby="modal_add_user" aria-hidden="true"
							 id="modal_add_user">
								<?php include 'create.phtml'; ?>
							</div>
							<h3><i class="fa fa-user"></i> Lista de usuários (<?= (count($users) === 1)?'1 usuário':count($users).' usuários'?>)</h3>
						</div>
						<!-- end card-header -->
						<div class="card-body">
							<div class="table-responsive">
								<table class="table table-hover" id="datatable">
									<thead>
										<tr>
											<th width="50">#</th>
											<th>Usuários</th>
											<th width="380"></th>
										</tr>
									</thead>
									<tbody>
										<?php foreach($users as $value){ ?>
										<tr>
											<th>
												<?= $value['id_usuario'] ?>
											</th>
											<td>
												<strong><?= $value['nome'] ?></strong> <br />
												<small><?= $value['email'] ?></small>
											</td>
											
											<td>
												
													<a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_edit_user_<?= $value['id_usuario'] ?>">
														<i class="fa fa-pencil" aria-hidden="true"></i><span>&nbsp;Editar</span>
													</a>
												
												<div class="modal custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_edit_user_<?= $value['id_usuario'] ?>">
													<div class="modal-dialog">
														<div class="modal-content">
															<form role="form" action="<?= PATH ?>/admin/users/<?= $value['id_usuario'] ?>" method="post" data-parsley-validate novalidate>
																<div class="modal-header">
																	<h5 class="modal-title">Editar usuário</h5>
																	<button type="button" class="close" data-dismiss="modal">
																		<span aria-hidden="true">&times;</span>
																		<span class="sr-only">Close</span>
																	</button>
																</div>
																<div class="modal-body">
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label	for="desperson-<?= $value['id_usuario'] ?>">Nome*</label>
																				<input	type="text" 
																						id="desperson-<?= $value['id_usuario'] ?>" 
																						name="nome" 
																						class="form-control" 
																						parsley-trigger="change" 
																						placeholder="Enter user name"
																						value="<?= $value['nome'] ?>"
																						required/>
																			</div>
																		</div>
																	</div>
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label  for="deslogin-<?= $value['id_usuario'] ?>">Login*</label>
																				<input  type="login" 
																						id="deslogin-<?= $value['id_usuario'] ?>" 
																						name="login" 
																						class="form-control"
																						value="<?= $value['login'] ?>"
																						required />
																			</div>
																		</div>																		
																	</div>
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label	for="desemail-<?= $value['email'] ?>">E-mail*</label>
																				<input	type="email"
																						id="desemail-<?= $value['email'] ?>" 
																						name="email"
																						class="form-control" 
																						data-parsley-type="email"
																						value="<?= $value['email'] ?>" 
																						required/>
																			</div>
																		</div>
																	</div>																	
																	<div class="row">																		
																		<div class="col-lg-6">
																			<div class="form-group">
																				<label>Ativo</label>
																				<select name="ativo" class="form-control">
																					<?php if($value['ativo'] == 1): ?>
																						<option value="1" selected>SIM</option>
																						<option value="0" >NÃO</option>
																					<?php else: ?>
																						<option value="1" >SIM</option>
																						<option value="0" selected>NÃO</option>
																					<?php endif; ?>
																				</select>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="modal-footer">
																	<button type="submit" class="btn btn-primary">Salvar</button>
																</div>
															</form>
														</div>
													</div>
												</div>
												
													<a href="#" class="btn btn-light btn-sm" data-toggle="modal" data-target="#modal_edit_pass_<?= $value['id_usuario'] ?>">
														<i class="fa fa-unlock-alt" aria-hidden="true"></i><span>&nbsp;Alterar Senha</span>
													</a>
												
												<div class="modal custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_edit_pass_<?= $value['id_usuario'] ?>">
													<div class="modal-dialog ">
														<div class="modal-content">
															<form role="form" action="<?= PATH ?>/admin/users/<?= $value['id_usuario']?>/password" method="post" data-parsley-validate>
																<div class="modal-header">
																	<h5 class="modal-title">Alterar Senha</h5>
																	<button type="button" class="close" data-dismiss="modal">
																		<span aria-hidden="true">&times;</span>
																		<span class="sr-only">Close</span>
																	</button>
																</div>
																<div class="modal-body">
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label	for="new_pass-<?= $value['id_usuario'] ?>">Nova Senha</label>
																				<input	type="password" 
																						id="new_pass-<?= $value['id_usuario'] ?>" 
																						class="form-control" 
																						name="senha"		
																						data-parsley-length="[6, 10]"																	 
																						placeholder="Nova senha"
																						required/>
																			</div>
																		</div>
																	</div>
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label	for="confirm-<?= $value['id_usuario'] ?>">Confirme a senha</label>
																				<input	type="password" 
																						id="confirm-<?= $value['id_usuario'] ?>" 
																						name="senha-confirm"
																						class="form-control" 
																						placeholder="Confirme a nova senha"
																						parsley-trigger="change"																						
																						data-parsley-equalto="#new_pass-<?= $value['id_usuario'] ?>"
																						required/>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="modal-footer">
																	<input type="hidden" name="user_id" value="5" />
																	<button type="submit" class="btn btn-primary">Salvar</button>
																</div>
															</form>
														</div>
													</div>
												</div>
												
											
												
													<a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal_remove_<?= $value['id_usuario'] ?>">
														<i class="fa fa-trash" aria-hidden="true"></i><span>&nbsp;Excluir</span></a>
													<div class="modal custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_remove_<?= $value['id_usuario'] ?>">
														<?= printAlert("Deseja realmente remover esse usuário?", PATH."/admin/users/".$value['id_usuario']."/delete"); ?>
													</div>		
												
											</td>
										</tr>
										<?php } ?>
									</tbody>
								</table>
							</div>

						</div>
						<!-- end card-body -->

					</div>
					<!-- end card -->

				</div>
				<!-- end col -->

			</div>
			<!-- end row -->

		</div>
		<!-- END container-fluid -->

	</div>
	<!-- END content -->

</div>
<!-- END content-page -->