<div class="content-page">

	<!-- Start content -->
	<div class="content">

		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-12">
					<div class="breadcrumb-holder">
						<h1 class="main-title float-left">Categorias</h1>
						<ol class="breadcrumb float-right">
							<li class="breadcrumb-item">Home</li>
							<li class="breadcrumb-item active">Categorias</li>
						</ol>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<!-- end row -->

			<?= message('message') ?>
		
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
					<div class="card mb-3">
						<div class="card-header">
							<span class="pull-right">							
								<button class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal_add">
									<i class="fa fa-plus" aria-hidden="true"></i> Adicionar nova categoria
								</button>							
							</span>
							<div class="modal custom-modal" tabindex="-1" role="dialog" aria-labelledby="modal_add" aria-hidden="true"
							 id="modal_add">
								<?php include 'create.phtml'; ?>
							</div>
							<h3><i class="fa fa-sitemap"></i> Lista de categorias (<?= (count($categorias) === 1)?'1 categoria':count($categorias).' categorias'?>)</h3>
						</div>
						<!-- end card-header -->
						<div class="card-body">
							<div class="table-responsive">
								<table class="table table-hover" id="datatable">
									<thead>
										<tr>
											<th width="50">#</th>
											<th>Categoria</th>
											<th width="180px"></th>
										</tr>
									</thead>
									<tbody>
										<?php foreach($categorias as $value){ ?>
										<tr>
											<th>
												<?= $value['id_categoria'] ?>
											</th>
											<td>
												<strong><?= $value['nome'] ?></strong> <br />												
											</td>
											
											<td>
												
												<a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_edit_<?= $value['id_categoria'] ?>">
													<i class="fa fa-pencil" aria-hidden="true"></i><span>&nbsp;Editar</span>
												</a>
												
												<div class="modal custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_edit_<?= $value['id_categoria'] ?>">
													<div class="modal-dialog">
														<div class="modal-content">
															<form role="form" action="<?= PATH ?>/admin/categorias/<?= $value['id_categoria'] ?>" method="post" data-parsley-validate novalidate>
																<div class="modal-header">
																	<h5 class="modal-title">Editar usuário</h5>
																	<button type="button" class="close" data-dismiss="modal">
																		<span aria-hidden="true">&times;</span>
																		<span class="sr-only">Close</span>
																	</button>
																</div>
																<div class="modal-body">
																	<div class="row">
																		<div class="col-lg-12">
																			<div class="form-group">
																				<label	for="nome-<?= $value['id_categoria'] ?>">Nome*</label>
																				<input	type="text" 
																						id="nome-<?= $value['id_categoria'] ?>" 
																						name="nome" 
																						class="form-control" 
																						parsley-trigger="change" 
																						placeholder="Digite o nome da categoria"
																						value="<?= $value['nome'] ?>"
																						required/>
																			</div>
																		</div>
																	</div>																																	
																	<div class="row">																		
																		<div class="col-lg-6">
																			<div class="form-group">
																				<label>Ativo</label>
																				<select name="ativo" class="form-control">
																					<?php if($value['ativo'] == 1): ?>
																						<option value="1" selected>SIM</option>
																						<option value="0" >NÃO</option>
																					<?php else: ?>
																						<option value="1" >SIM</option>
																						<option value="0" selected>NÃO</option>
																					<?php endif; ?>
																				</select>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="modal-footer">
																	<button type="submit" class="btn btn-primary">Salvar</button>
																</div>
															</form>
														</div>
													</div>
												</div>
												<a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal_remove_<?= $value['id_categoria'] ?>">
													<i class="fa fa-trash" aria-hidden="true"></i><span>&nbsp;Excluir</span></a>
												<div class="modal custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_remove_<?= $value['id_categoria'] ?>">
													<?= printAlert("Deseja realmente remover essa categoria?", PATH."/admin/categorias/".$value['id_categoria']."/delete"); ?>
												</div>	
											</td>
										</tr>
										<?php } ?>
									</tbody>
								</table>
							</div>

						</div>
						<!-- end card-body -->

					</div>
					<!-- end card -->

				</div>
				<!-- end col -->

			</div>
			<!-- end row -->

		</div>
		<!-- END container-fluid -->

	</div>
	<!-- END content -->

</div>
<!-- END content-page -->