
    <div class="content-page">
	
		<!-- Start content -->
        <div class="content">
            
			<div class="container-fluid">

					
						<div class="row">
								<div class="col-xl-12">
										<div class="breadcrumb-holder">
												<h1 class="main-title float-left">Meu Perfil</h1>
												<ol class="breadcrumb float-right">
													<li class="breadcrumb-item">Home</li>
													<li class="breadcrumb-item active">Perfil</li>
												</ol>
												<div class="clearfix"></div>
										</div>
								</div>
						</div>
						<!-- end row -->
				
						<div class="row">
							
									<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">						
										<div class="card mb-3">
											<div class="card-header">
												<h3><i class="fa fa-user"></i> Detalhes do perfil</h3>								
											</div>
												
											<div class="card-body">
												
												
												<form action="#" method="post" enctype="multipart/form-data">
								
												<div class="row">	
												
												<div class="col-lg-9 col-xl-9">
													
													<div class="row">				
														<div class="col-lg-6">
														<div class="form-group">
														<label>Nome completo (obrigatório)</label>
														<input class="form-control" name="name" type="text" value="Administrator" required />
														</div>
														</div>

														<div class="col-lg-6">
														<div class="form-group">
														<label>Email (obrigatório)</label>
														<input class="form-control" name="email" type="email" value="office@website.com" required />
														</div>
														</div>  
													</div>
													
													<div class="row">				
														<div class="col-lg-6">
														<div class="form-group">
														<label>Senha</label>
														<input class="form-control" name="password" type="password" value="" />
														</div>
														</div>              			                                
														
														<div class="col-lg-6">
														<div class="form-group">
														<label>Skype</label>
														<input class="form-control" name="skype" type="text" value="skypeid" />
														</div>
														</div>   
													</div>
													
													<div class="row">
														<div class="col-lg-12">
														<button type="button" class="btn btn-primary">Editar Perfil</button>
														</div>
													</div>
												
												</div>
												
												
												
												<div class="col-lg-3 col-xl-3 border-left">
													<b>Ultima atividade</b>: Dec 06 2017, 22:23	
													<br />
													<b>Data de cadastro: </b>: Nov 24 2017, 20:32	
													<br />
													<b>IP registrado: </b>: 123.456.789
													
													<div class="m-b-10"></div>
													
													<div id="avatar_image">
														<img style="max-width:100px; height:auto;" src="<?= PATH ?>assets/admin/images/avatars/avatar7.png" />
														<br />
														<i class="fa fa-trash-o fa-fw"></i> <a class="delete_image" href="#">Remover avatar</a>
																	
													</div>  
													<div id="image_deleted_text"></div>                      

													
													<div class="m-b-10"></div>
													
													<div class="form-group">
													<label>Alterar avatar</label> 
													<input type="file" name="image" class="form-control">
													</div>
													
												</div>
												</div>								
												
												</form>										
												
								</div>	
								<!-- end card-body -->								
									
							</div>
							<!-- end card -->					

						</div>
						<!-- end col -->	
															
					</div>
					<!-- end row -->	


            </div>
			<!-- END container-fluid -->

		</div>
		<!-- END content -->

    </div>
	<!-- END content-page -->
 