<link rel="stylesheet" href="<?= PATH ?>assets/site/css/form-cadastro.css">
<div class="align-items-center d-flex py-5 cover section-primary" style="background-image: url('<?= PATH ?>assets/site/img/styleguide/cover_light.jpg');">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <form action="<?= PATH ?>admin/cardapios/create" method="post">
          <h3 class="text-center pb-4 py-4">1º - Escolha um layout</h3>
          <div class="form-row justify-content-center">
            <div class="radio-tile-group">
              <div class="input-container">
                <input class="radio-button" type="radio" value="3" name="layout">
                <div class="radio-tile text-center">
                  <img class="m-4" src="<?= PATH ?>assets/site/img/menu-3.svg" width="175" height="224" alt="Card image cap">
                  <h5 class="text-dark"><b>1 Coluna simples</b></h5>
                  <p class="text-dark">Banner no topo, titulo da categoria, lista de produtos simples</p>
                </div>
              </div>
              <div class="input-container">
                <input class="radio-button" type="radio" value="2" name="layout">
                <div class="radio-tile text-center">
                  <img class="m-4" src="<?= PATH ?>assets/site/img/menu-2.svg" width="175" height="224" alt="Card image cap">
                  <h5 class="text-dark"><b>2 Coluna simples</b></h5>
                  <p class="text-dark">Banner no topo 2 colunas com a categoria e lista de produtos simples</p>
                </div>
              </div>
              <div class="input-container">
                <input class="radio-button" type="radio" value="1" name="layout">
                <div class="radio-tile text-center">
                  <img class="m-4" src="<?= PATH ?>assets/site/img/menu-1.svg" width="175" height="224" alt="Card image cap">
                  <h5 class="text-dark"><b>Grade com imagens</b></h5>
                  <p class="text-dark">Banner no topo, 3 colunas,<br>com cada item possui uma foto, titulo do item, descrição e preço</p>
                </div>
              </div>
            </div>
          </div>
          <div class="my-5 py-1" id="temas" tabindex="-1"></div>
          <h3 class="text-center pt-4">2º - Escolha um tema</h3>
          <h6 class="text-center pb-4">Pode ser alterado depois</h6>
          <div class="form-row justify-content-center">
            <div class="radio-tile-group">
              <div class="input-container">
                <input class="radio-button" type="radio" value="1" name="tema">
                <div class="radio-tile text-center">
                  <h4 class="text-dark">Tema 1</h4>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#dc3545">Cor principal</div>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#292524">Cor secundaria</div>
                  <div class="rounded bg-transparent border border-dark py-2 w-100 mb-2 font-weight-bold" style="color:#212529"><strong>Cor do texto escuro</strong></div>
                  <div class="rounded bg-dark py-2 w-100 mb-2 font-weight-bold" style="color:#ffffff"><strong>Cor do texto claro</strong></div>
                </div>
              </div>
              <div class="input-container">
                <input class="radio-button" type="radio" value="2" name="tema">
                <div class="radio-tile text-center">
                <h4 class="text-dark">Tema 2</h4>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#a23052">Cor principal</div>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#702428">Cor secundaria</div>
                  <div class="rounded bg-transparent border border-dark font-weight-bold py-2 w-100 mb-2" style="color:#2e2e2e"><strong>Cor do texto escuro</strong></div>
                  <div class="rounded bg-dark py-2 w-100 mb-2 font-weight-bold" style="color:#d6d4d4"><strong>Cor do texto claro</strong></div>
                </div>
              </div>
              <div class="input-container">
                <input class="radio-button" type="radio" value="3" name="tema">
                <div class="radio-tile text-center">
                <h4 class="text-dark">Tema 3</h4>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#dc3545">Cor principal</div>
                  <div class="rounded py-2 w-100 mb-2 font-weight-bold" style="background-color:#292524">Cor secundaria</div>
                  <div class="rounded bg-transparent border font-weight-bold border-dark py-2 w-100 mb-2" style="color:#212529"><strong>Cor do texto escuro</strong></div>
                  <div class="rounded bg-dark py-2 w-100 font-weight-bold mb-2" style="color:#ffffff"><strong>Cor do texto claro</strong></div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row py-5">
            <button type="submit" name="" id="btn-submit" class="btn btn-success py-3 px-5 btn-lg mx-auto w-75">Continuar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  $("input[name=layout]").on('change', () => {
    var target = $("#temas");
    $('html, body').animate({
        scrollTop: target.offset().top
      },
      500,
      function() {
        // Callback after animation
        // Must change focus!
        var $target = $(target);
        $target.focus();
        if ($target.is(":focus")) { // Checking if the target was focused
          return false;
        } else {
          $target.attr('tabindex', '-1'); // Adding tabindex for elements not focusable
          $target.focus(); // Set focus again
        };
      });
  });
</script>