<div class="align-items-center d-flex py-5 cover section-primary" style="background-image: url('<?= PATH ?>assets/site/img/styleguide/cover_light.jpg<?= PATH ?>');">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="text-center pb-4 py-4">1º - Escolha um template</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="text-center bg-template bg-light-opacity py-3"> <img class="card-img-top mx-auto w-75 px-2 pt-3" src="<?= PATH ?>assets/site/img/menu-1.svg" alt="Card image cap">
            <div class="card-body">
              <h5 class="text-dark pb-2"><b>1 Coluna Simples</b></h5>
              <p class="card-text text-dark">Banner no topo, titulo da categoria, item possui apenas o titulo e o preço</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="text-center bg-template bg-light-opacity py-3"> <img class="card-img-top mx-auto w-75 px-2 pt-3" src="<?= PATH ?>assets/site/img/menu-2.svg" alt="Card image cap">
            <div class="card-body">
              <h5 class="text-dark pb-2"><b>Itens com foto</b></h5>
              <p class="card-text text-dark">Banner no topo, grid de 3 colunas, com cada item possui uma foto, titulo do item, descrição e preço</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="text-center bg-template bg-light-opacity py-3"> <img class="card-img-top mx-auto w-75 px-2 pt-3" src="<?= PATH ?>assets/site/img/menu-3.svg" alt="Card image cap">
            <div class="card-body">
              <h5 class="text-dark pb-2"><b>2 Colunas + imagem</b></h5>
              <p class="card-text text-dark">Banner no topo, grid de 3 colunas, com cada item possui uma foto, titulo do item, descrição e preço</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>