<style>
.parsley-errors-list>li {
    font-size: 12px;
    list-style: none;
    color: white !important;
    margin-top: 5px;
}

::-webkit-scrollbar {
width:10px;
height: 10px;
}
 
/* aqui é para personalizar o fundo da barra, neste caso estou colocando um fundo cinza escuro*/
::-webkit-scrollbar-track {
background:#333;
}
 
/* aqui é a alça da barra, que demonstra a altura que você está na página
estou colocando uma cor azul clara nela*/
::-webkit-scrollbar-thumb {
background: #F55e61;
}
</style>

<div class="align-items-center d-flex py-5 cover section-primary" style="background-image: url('<?= PATH ?>assets/site/img/styleguide/cover_light.jpg');">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 align-self-center text-lg-left text-center">
          <img class="img-fluid d-block mx-auto" src="<?= PATH ?>assets/site/img/icon-ecardapio-white.png">
          <p class="mb-5 text-center">eCardapio - Cardápio digital</p>
        </div>
        <div class="col-lg-5 p-3 bg-form">
          <!--form cadastro-->
          <form id="form-cadastro" action="<?= PATH ?>cadastrar" class="section-light pt-2 px-4" method="post" data-parsley-validate novalidate>
            <h4 class="mb-3 text-center">Crie o seu agora mesmo</h4>
            <?= message('message') ?>
            <div class="form-group">
              <label>Nome do comércio</label>
              <input required parsley-trigger="change" name="estabelecimento" class="form-control" placeholder="Digite o nome do comércio"> </div>            
              <?= @$erro_cadastro['estabelecimento'][0] ?>
            <div class="form-group">
              <label>E-mail</label>
              <input required parsley-trigger="change" name="email" type="email" class="form-control" placeholder="Digite seu email"> </div>
              <?= @$erro_cadastro['email'][0] ?>
              <div class="form-group">
              <label>Senha</label>
              <input required parsley-trigger="change" name="senha" type="password" class="form-control" placeholder="Digite uma senha"> </div>
            <button type="submit" class="btn mt-4 btn-block p-2 btn-secondary font-20"> Criar cardápio </button>
            <button type="button" class="btn botao-login btn-block p-2 font-20 btn-link text-white">
              <b>Já possuo conta</b>
            </button>
          </form>

          <!--form login-->
          <form id="form-login" style="display: none;" action="<?= PATH ?>logar" class="section-light pt-4 pb-2 px-4" method="post" data-parsley-validate novalidate>
            <h4 class="mb-3 text-center">Entrar</h4>
            <div class="alert alert-primary text-center" style="display: none;" id="msg-error">Usuário ou senha inválidos</div>
            <div class="form-group">
              <label>E-mail</label>
              <input required parsley-trigger="change" name="email" type="email" class="form-control" placeholder="Digite seu email"> </div>
            <div class="form-group">
              <label>Senha</label>
              <input required parsley-trigger="change" name="senha" type="password" class="form-control" placeholder="Digite sua senha"> </div>
            <button type="button" id="btn-submit-login" class="btn mt-4 btn-block p-2 btn-secondary font-20">Entrar</button>
            <button id="botao-cadastro" type="button" class="btn btn-block p-2 font-20 btn-link text-white">
              <b>Não possuo conta</b>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

<div id="fundo">
  <!-- Carousel venue -->
  <div class="py-5 " id="sobre">
    <div class="container">
      <div class="row bg-primary p-4">
        <div class="p-4 col-md-6 bg-light">
          <h2>Como funciona ?</h2><br>
          <p class="my-4" style="margin-top: 0px !important; margin-bottom: 0px !important;">É muito simples!! Basta realizar um cadastro rápido e gratuito e você já poderá trabalhar sua criatividade e desenvolver os mais váriados tipos de cardápios.<br>
            <br>Você poderá imprimir e compartilhar seu cardápio com QRCode ou em suas redes sociais, muito intuitivo e fácil de utilizar.<br>
            <br>Disponibilizamos planos com diferentes layouts e funcionalidades, porém é possível sim ser utilizado gratuitamente. </p>
        </div>
        <div class="p-0 col-md-6">
          <div class="carousel slide" data-ride="carousel" id="carousel1">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid w-100" src="<?= PATH ?>assets/site/img/restaurant/venue_1_light.jpg" atl="first slide"> </div>
              <div class="carousel-item">
                <img class="d-block img-fluid w-100" src="<?= PATH ?>assets/site/img/restaurant/venue_3_light.jpg" data-holder-rendered="true"> </div>
              <div class="carousel-item">
                <img class="d-block img-fluid w-100" src="<?= PATH ?>assets/site/img/restaurant/venue_2_light.jpg" data-holder-rendered="true"> </div>
              <div class="carousel-item">
                <img class="d-block img-fluid w-100" src="<?= PATH ?>assets/site/img/restaurant/venue_4_light.jpg" data-holder-rendered="true"> </div>
            </div>
            <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Menu -->
  <div class="content-page" id="planos">
    <section class="pricing py-5">
        <div class="container-fluid">
            <div class="row" style="justify-content: center; align-items: center;">
                <!-- Free Tier -->
                <div class="col-lg-4">
                    <div class="card mb-5 mb-lg-0">
                    <div class="card-body">
                        <h5 class="card-title text-muted text-uppercase text-center">Grátis</h5>
                        <h6 class="card-price text-center">R$0<span class="period">/mensal</span></h6>
                        <hr>
                        <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Criação de cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Impressão do cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Customização<small><strong>(parcial)</strong></small></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Compartilhamento via QRCode</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Remoção de anúncios</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Wallpaper para cardápio</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Mais opções de layouts</li>
                        <li class="text-muted"><span class="fa-li"><i class="fa fa-times"></i></span>Suporte exclusivo</li>
                        </ul>
                        <button class="btn btn-block btn-primary text-uppercase assinar-plano">Saiba mais!</button>
                    </div>
                    </div>
                </div>
                
                <!-- Pro Tier -->
                <div class="col-lg-4">
                    <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-muted text-uppercase text-center">Pro</h5>
                        <h6 class="card-price text-center">R$49<span class="period">/mensal</span></h6>
                        <hr>
                        <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fa fa-check"></i></span><strong>Criação de cardápio</strong></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Impressão do cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Customização<small><strong>(parcial)</strong></small></li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Compartilhamento via QRCode</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Remoção de anúncios</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Wallpaper para cardápio</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Mais opções de layouts</li>
                        <li><span class="fa-li"><i class="fa fa-check"></i></span>Suporte exclusivo</li>
                        </ul>
                        <button class="btn btn-block btn-primary text-uppercase assinar-plano">Saiba mais!</button>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  </div>
</div>

  <script>
    $(".botao-login").on("click", function(){
      $("#form-cadastro").slideUp("2000", function(){
        $("#form-login").slideDown();
      });
    });

    $("#botao-cadastro").on("click", function(){
      $("#form-login").slideUp("2000", function(){
        $("#form-cadastro").slideDown();
      });
    });
    
    $("#btn-submit-login").on("click", function(e){
     // e.preventDefault();
      $(this).html('<i class="fa fa-circle-o-notch fa-spin fa-lg fa-fw"></i>');
      let data = $("#form-login").serialize();
      $.post("<?= PATH ?>verify_login", data)
        .then((res) => {
        console.log(res);
        if(res.status == "success"){
          $("#form-login").submit();
        }else{
          $(this).text("Entrar");
          $('#msg-error').fadeIn();
        }
      });
    });
  
  </script>